kind: DataSetConfiguration
apiVersion: client.uor-framework.io/v1alpha1
collection:
  files:
    - file: '*.whl'
      attributes:
        pyindex: true
    - file: '*.tar.gz'
      attributes:
        pyindex: true
    - file: 'bottle/*.whl'
      attributes:
        package: 'bottle'
    - file: 'bottle/*.tar.gz'
      attributes:
        package: 'bottle'
    - file: 'iniconfig/*.whl'
      attributes:
        package: 'iniconfig'
    - file: 'iniconfig/*.tar.gz'
      attributes:
        package: 'iniconfig'
    - file: 'isodate/*.whl'
      attributes:
        package: 'isodate'
    - file: 'isodate/*.tar.gz'
      attributes:
        package: 'isodate'
    - file: 'pymetronome/*.whl'
      attributes:
        package: 'pymetronome'
    - file: 'pymetronome/*.tar.gz'
      attributes:
        package: 'pymetronome'
